# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('urlHash', models.CharField(default='', max_length=200)),
                ('code', models.TextField(default='')),
            ],
        ),
    ]
