# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
